---
version: "3"
services:
    impf-bot:
        image: pfuenzle/impf-bot
        container_name: impf-bot
        volumes:
            - ./config.properties:/app/src/main/resources/config.properties
        ports:
            - 5901:5901
            - 6901:6901
        environment:
            - VNC_PASSWORD=CHANGEME
        restart: unless-stopped
    
